language: dart

dart:
  - 1.24.3
  - stable

script:
  - pub get
  - dartfmt --set-exit-if-changed --dry-run lib bin test tool
  - pub run dependency_validator -x upgrade/ -i dart_dev
  - dartanalyzer bin lib test
  - pub run test --concurrency=4 -p vm --reporter=expanded test/vm/

