language: dart

jobs:
  include:
    - dart: 2.4.0
      name: "SDK: 2.4.0"
      script:
        - dartanalyzer bin lib test
        - pub run test
    - dart: stable
      name: "SDK: stable"
      script:
        - dartanalyzer bin lib test
        - dartfmt -n --set-exit-if-changed lib bin test tool
        - pub run test
    - dart: dev
      name: "SDK: dev"
      script:
        - dartanalyzer bin lib test
        - pub run test
