name: 'abide'
version: 1.6.5
description: A command line tool to manage analysis_options.yaml and check if it abides by requirements.
authors: 
  - Workiva Client Platform Team <clientplatform@workiva.com>
  - Rob Becker <rob.becker@workiva.com>
  - Sebastian Malysa <sebastian.malysa@workiva.com>
  
homepage: https://github.com/Workiva/abide

environment:
  sdk: '>=1.23.0 <3.0.0'

executables:
  abide:

dependencies:
  args:  ^2.0.0
  dart2_constant: ^1.0.0
  meta: ^1.1.6
  resource: ^2.0.0
  yaml: ^3.0.0

dev_dependencies:
  dart_dev:
    git:
      url: git@github.com:kyleferguson-wk/dart_dev.git
      ref: master
  dependency_validator:
    git:
      url: git@github.com:kyleferguson-wk/dependency_validator.git
      ref: master
  test: '>=0.12.34 <2.0.0'
