name: 'abide'
version: 1.6.9
description: A command line tool to manage analysis_options.yaml and check if it abides by requirements.
  
homepage: https://github.com/Workiva/abide

environment:
  sdk: ">=2.11.0 <3.0.0"

executables:
  abide:

dependencies:
  args:  ^1.4.4
  meta: '>=1.2.2 <1.7.0'
  resource: ^2.0.0
  yaml: ^2.1.12

dev_dependencies:
  dart_dev: ^2.0.0
  dependency_validator: ^1.1.2
  test: ^1.15.7

dependency_overrides:
  yaml: 3.0.0
