name: 'abide_upgrade'
version: 1.0.0
description: A command line tool to update abide.yaml
author: Rob Becker <rob.becker@workiva.com>
homepage: https://github.com/Workiva/abide

environment:
  sdk: '>=2.4.0 <3.0.0'

executables:
  abide_upgrade: upgrade

dependencies:
  yaml: ^2.2.0
  linter: ">=0.1.104" # Use the latest published linter